# Bitbucket build configuration for Maven.
# https://support.atlassian.com/bitbucket-cloud/docs/java-with-bitbucket-pipelines/
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# https://hub.docker.com/_/maven
image: maven:3.8.4-openjdk-11

pipelines:
  default:
    - step:
        script:
          - mvn clean install -s settings.xml -Pexamples
